namespace PhasmoSaveEditor
{
    public class PhasmoData
    {
        public RepellentTier RepellentTier{ get; set; }
        public IgniterTier IgniterTier{ get; set; }
        public SoundSensorTier SoundSensorTier{ get; set; }
        public SpiritBoxTier SpiritBoxTier{ get; set; }
        public HeadGearTier HeadGearTier{ get; set; }
        public CrucifixTier CrucifixTier{ get; set; }
        public VideoCameraTier VideoCameraTier{ get; set; }
        public GhostWritingBookTier GhostWritingBookTier{ get; set; }
        public EMFReaderTier EMFReaderTier{ get; set; }
        public UVLightTier UVLightTier{ get; set; }
        public SaltTier SaltTier{ get; set; }
        public ParabolicMicrophoneTier ParabolicMicrophoneTier{ get; set; }
        public FlashlightTier FlashlightTier{ get; set; }
        public TripodTier TripodTier{ get; set; }
        public DOTSProjectorTier DOTSProjectorTier{ get; set; }
        public ThermometerTier ThermometerTier{ get; set; }
        public FirelightTier FirelightTier{ get; set; }
        public MotionSensorTier MotionSensorTier{ get; set; }
        public PhotoCameraTier PhotoCameraTier{ get; set; }
        public SanityMedicationTier SanityMedicationTier{ get; set; }
        public Experience Experience{ get; set; }
        public PlayersMoney PlayersMoney{ get; set; }
        public Level Level{ get; set; }
        public Prestige Prestige{ get; set; }
        public RepellentInventory RepellentInventory{ get; set; }
        public IgniterInventory IgniterInventory{ get; set; }
        public SoundSensorInventory SoundSensorInventory{ get; set; }
        public SpiritBoxInventory SpiritBoxInventory{ get; set; }
        public HeadGearInventory HeadGearInventory{ get; set; }
        public CrucifixInventory CrucifixInventory{ get; set; }
        public VideoCameraInventory VideoCameraInventory{ get; set; }
        public GhostWritingBookInventory GhostWritingBookInventory{ get; set; }
        public EMFReaderInventory EMFReaderInventory{ get; set; }
        public UVLightInventory UVLightInventory{ get; set; }
        public SaltInventory SaltInventory{ get; set; }
        public ParabolicMicrophoneInventory ParabolicMicrophoneInventory{ get; set; }
        public FlashlightInventory FlashlightInventory{ get; set; }
        public TripodInventory TripodInventory{ get; set; }
        public DOTSProjectorInventory DOTSProjectorInventory{ get; set; }
        public ThermometerInventory ThermometerInventory{ get; set; }
        public FirelightInventory FirelightInventory{ get; set; }
        public MotionSensorInventory MotionSensorInventory{ get; set; }
        public PhotoCameraInventory PhotoCameraInventory{ get; set; }
        public SanityMedicationInventory SanityMedicationInventory{ get; set; }
        public RepellentTierTwoUnlocked RepellentTierTwoUnlocked{ get; set; }
        public IgniterTierTwoUnlocked IgniterTierTwoUnlocked{ get; set; }
        public SoundSensorTierTwoUnlocked SoundSensorTierTwoUnlocked{ get; set; }
        public SpiritBoxTierTwoUnlocked SpiritBoxTierTwoUnlocked{ get; set; }
        public HeadGearTierTwoUnlocked HeadGearTierTwoUnlocked{ get; set; }
        public CrucifixTierTwoUnlocked CrucifixTierTwoUnlocked{ get; set; }
        public VideoCameraTierTwoUnlocked VideoCameraTierTwoUnlocked{ get; set; }
        public GhostWritingBookTierTwoUnlocked GhostWritingBookTierTwoUnlocked{ get; set; }
        public EMFReaderTierTwoUnlocked EMFReaderTierTwoUnlocked{ get; set; }
        public UVLightTierTwoUnlocked UVLightTierTwoUnlocked{ get; set; }
        public SaltTierTwoUnlocked SaltTierTwoUnlocked{ get; set; }
        public ParabolicMicrophoneTierTwoUnlocked ParabolicMicrophoneTierTwoUnlocked{ get; set; }
        public FlashlightTierTwoUnlocked FlashlightTierTwoUnlocked{ get; set; }
        public TripodTierTwoUnlocked TripodTierTwoUnlocked{ get; set; }
        public DOTSProjectorTierTwoUnlocked DOTSProjectorTierTwoUnlocked{ get; set; }
        public ThermometerTierTwoUnlocked ThermometerTierTwoUnlocked{ get; set; }
        public FirelightTierTwoUnlocked FirelightTierTwoUnlocked{ get; set; }
        public MotionSensorTierTwoUnlocked MotionSensorTierTwoUnlocked{ get; set; }
        public PhotoCameraTierTwoUnlocked PhotoCameraTierTwoUnlocked{ get; set; }
        public SanityMedicationTierTwoUnlocked SanityMedicationTierTwoUnlocked{ get; set; }
        public RepellentTierThreeUnlocked RepellentTierThreeUnlocked{ get; set; }
        public IgniterTierThreeUnlocked IgniterTierThreeUnlocked{ get; set; }
        public SoundSensorTierThreeUnlocked SoundSensorTierThreeUnlocked{ get; set; }
        public SpiritBoxTierThreeUnlocked SpiritBoxTierThreeUnlocked{ get; set; }
        public HeadGearTierThreeUnlocked HeadGearTierThreeUnlocked{ get; set; }
        public CrucifixTierThreeUnlocked CrucifixTierThreeUnlocked{ get; set; }
        public VideoCameraTierThreeUnlocked VideoCameraTierThreeUnlocked{ get; set; }
        public GhostWritingBookTierThreeUnlocked GhostWritingBookTierThreeUnlocked{ get; set; }
        public EMFReaderTierThreeUnlocked EMFReaderTierThreeUnlocked{ get; set; }
        public UVLightTierThreeUnlocked UVLightTierThreeUnlocked{ get; set; }
        public SaltTierThreeUnlocked SaltTierThreeUnlocked{ get; set; }
        public ParabolicMicrophoneTierThreeUnlocked ParabolicMicrophoneTierThreeUnlocked{ get; set; }
        public FlashlightTierThreeUnlocked FlashlightTierThreeUnlocked{ get; set; }
        public TripodTierThreeUnlocked TripodTierThreeUnlocked{ get; set; }
        public DOTSProjectorTierThreeUnlocked DOTSProjectorTierThreeUnlocked{ get; set; }
        public ThermometerTierThreeUnlocked ThermometerTierThreeUnlocked{ get; set; }
        public FirelightTierThreeUnlocked FirelightTierThreeUnlocked{ get; set; }
        public MotionSensorTierThreeUnlocked MotionSensorTierThreeUnlocked{ get; set; }
        public PhotoCameraTierThreeUnlocked PhotoCameraTierThreeUnlocked{ get; set; }
        public SanityMedicationTierThreeUnlocked SanityMedicationTierThreeUnlocked{ get; set; }
        public RepellentTierOneUnlocked RepellentTierOneUnlocked{ get; set; }
        public IgniterTierOneUnlocked IgniterTierOneUnlocked{ get; set; }
        public SoundSensorTierOneUnlocked SoundSensorTierOneUnlocked{ get; set; }
        public SpiritBoxTierOneUnlocked SpiritBoxTierOneUnlocked{ get; set; }
        public HeadGearTierOneUnlocked HeadGearTierOneUnlocked{ get; set; }
        public CrucifixTierOneUnlocked CrucifixTierOneUnlocked{ get; set; }
        public VideoCameraTierOneUnlocked VideoCameraTierOneUnlocked{ get; set; }
        public GhostWritingBookTierOneUnlocked GhostWritingBookTierOneUnlocked{ get; set; }
        public EMFReaderTierOneUnlocked EMFReaderTierOneUnlocked{ get; set; }
        public UVLightTierOneUnlocked UVLightTierOneUnlocked{ get; set; }
        public SaltTierOneUnlocked SaltTierOneUnlocked{ get; set; }
        public ParabolicMicrophoneTierOneUnlocked ParabolicMicrophoneTierOneUnlocked{ get; set; }
        public FlashlightTierOneUnlocked FlashlightTierOneUnlocked{ get; set; }
        public TripodTierOneUnlocked TripodTierOneUnlocked{ get; set; }
        public DOTSProjectorTierOneUnlocked DOTSProjectorTierOneUnlocked{ get; set; }
        public ThermometerTierOneUnlocked ThermometerTierOneUnlocked{ get; set; }
        public FirelightTierOneUnlocked FirelightTierOneUnlocked{ get; set; }
        public MotionSensorTierOneUnlocked MotionSensorTierOneUnlocked{ get; set; }
        public PhotoCameraTierOneUnlocked PhotoCameraTierOneUnlocked{ get; set; }
        public SanityMedicationTierOneUnlocked SanityMedicationTierOneUnlocked{ get; set; }
    }
}
