using Newtonsoft.Json.Linq;
using PhasmoSaveEditor;

namespace PhasmophobiaSaveEditor
{
    public class PhasmoDataDeclaration
    {
        public PhasmoData values { get; set; }

        public PhasmoDataDeclaration(string jsonString)
        {
            JObject jObject = JObject.Parse(jsonString);

            values = new PhasmoData
            {
                RepellentTier = jObject["RepellentTier"]?.ToObject<RepellentTier>(),
                IgniterTier = jObject["IgniterTier"]?.ToObject<IgniterTier>(),
                SoundSensorTier = jObject["SoundSensorTier"]?.ToObject<SoundSensorTier>(),
                SpiritBoxTier = jObject["SpiritBoxTier"]?.ToObject<SpiritBoxTier>(),
                HeadGearTier = jObject["HeadGearTier"]?.ToObject<HeadGearTier>(),
                CrucifixTier = jObject["CrucifixTier"]?.ToObject<CrucifixTier>(),
                VideoCameraTier = jObject["VideoCameraTier"]?.ToObject<VideoCameraTier>(),
                GhostWritingBookTier = jObject["GhostWritingBookTier"]?.ToObject<GhostWritingBookTier>(),
                EMFReaderTier = jObject["EMFReaderTier"]?.ToObject<EMFReaderTier>(),
                UVLightTier = jObject["UVLightTier"]?.ToObject<UVLightTier>(),
                SaltTier = jObject["SaltTier"]?.ToObject<SaltTier>(),
                ParabolicMicrophoneTier = jObject["ParabolicMicrophoneTier"]?.ToObject<ParabolicMicrophoneTier>(),
                FlashlightTier = jObject["FlashlightTier"]?.ToObject<FlashlightTier>(),
                TripodTier = jObject["TripodTier"]?.ToObject<TripodTier>(),
                DOTSProjectorTier = jObject["DOTSProjectorTier"]?.ToObject<DOTSProjectorTier>(),
                ThermometerTier = jObject["ThermometerTier"]?.ToObject<ThermometerTier>(),
                FirelightTier = jObject["FirelightTier"]?.ToObject<FirelightTier>(),
                MotionSensorTier = jObject["MotionSensorTier"]?.ToObject<MotionSensorTier>(),
                PhotoCameraTier = jObject["PhotoCameraTier"]?.ToObject<PhotoCameraTier>(),
                SanityMedicationTier = jObject["SanityMedicationTier"]?.ToObject<SanityMedicationTier>(),
                Experience = jObject["Experience"]?.ToObject<Experience>(),
                PlayersMoney = jObject["PlayersMoney"]?.ToObject<PlayersMoney>(),
                Level = jObject["Level"]?.ToObject<Level>(),
                Prestige = jObject["Prestige"]?.ToObject<Prestige>(),
                RepellentInventory = jObject["RepellentInventory"]?.ToObject<RepellentInventory>(),
                IgniterInventory = jObject["IgniterInventory"]?.ToObject<IgniterInventory>(),
                SoundSensorInventory = jObject["SoundSensorInventory"]?.ToObject<SoundSensorInventory>(),
                SpiritBoxInventory = jObject["SpiritBoxInventory"]?.ToObject<SpiritBoxInventory>(),
                HeadGearInventory = jObject["HeadGearInventory"]?.ToObject<HeadGearInventory>(),
                CrucifixInventory = jObject["CrucifixInventory"]?.ToObject<CrucifixInventory>(),
                VideoCameraInventory = jObject["VideoCameraInventory"]?.ToObject<VideoCameraInventory>(),
                GhostWritingBookInventory = jObject["GhostWritingBookInventory"]?.ToObject<GhostWritingBookInventory>(),
                EMFReaderInventory = jObject["EMFReaderInventory"]?.ToObject<EMFReaderInventory>(),
                UVLightInventory = jObject["UVLightInventory"]?.ToObject<UVLightInventory>(),
                SaltInventory = jObject["SaltInventory"]?.ToObject<SaltInventory>(),
                ParabolicMicrophoneInventory = jObject["ParabolicMicrophoneInventory"]?.ToObject<ParabolicMicrophoneInventory>(),
                FlashlightInventory = jObject["FlashlightInventory"]?.ToObject<FlashlightInventory>(),
                TripodInventory = jObject["TripodInventory"]?.ToObject<TripodInventory>(),
                DOTSProjectorInventory = jObject["DOTSProjectorInventory"]?.ToObject<DOTSProjectorInventory>(),
                ThermometerInventory = jObject["ThermometerInventory"]?.ToObject<ThermometerInventory>(),
                FirelightInventory = jObject["FirelightInventory"]?.ToObject<FirelightInventory>(),
                MotionSensorInventory = jObject["MotionSensorInventory"]?.ToObject<MotionSensorInventory>(),
                PhotoCameraInventory = jObject["PhotoCameraInventory"]?.ToObject<PhotoCameraInventory>(),
                SanityMedicationInventory = jObject["SanityMedicationInventory"]?.ToObject<SanityMedicationInventory>(),
                RepellentTierTwoUnlocked = jObject["RepellentTierTwoUnlocked"]?.ToObject<RepellentTierTwoUnlocked>(),
                IgniterTierTwoUnlocked = jObject["IgniterTierTwoUnlocked"]?.ToObject<IgniterTierTwoUnlocked>(),
                SoundSensorTierTwoUnlocked = jObject["SoundSensorTierTwoUnlocked"]?.ToObject<SoundSensorTierTwoUnlocked>(),
                SpiritBoxTierTwoUnlocked = jObject["SpiritBoxTierTwoUnlocked"]?.ToObject<SpiritBoxTierTwoUnlocked>(),
                HeadGearTierTwoUnlocked = jObject["HeadGearTierTwoUnlocked"]?.ToObject<HeadGearTierTwoUnlocked>(),
                CrucifixTierTwoUnlocked = jObject["CrucifixTierTwoUnlocked"]?.ToObject<CrucifixTierTwoUnlocked>(),
                VideoCameraTierTwoUnlocked = jObject["VideoCameraTierTwoUnlocked"]?.ToObject<VideoCameraTierTwoUnlocked>(),
                GhostWritingBookTierTwoUnlocked = jObject["GhostWritingBookTierTwoUnlocked"]?.ToObject<GhostWritingBookTierTwoUnlocked>(),
                EMFReaderTierTwoUnlocked = jObject["EMFReaderTierTwoUnlocked"]?.ToObject<EMFReaderTierTwoUnlocked>(),
                UVLightTierTwoUnlocked = jObject["UVLightTierTwoUnlocked"]?.ToObject<UVLightTierTwoUnlocked>(),
                SaltTierTwoUnlocked = jObject["SaltTierTwoUnlocked"]?.ToObject<SaltTierTwoUnlocked>(),
                ParabolicMicrophoneTierTwoUnlocked = jObject["ParabolicMicrophoneTierTwoUnlocked"]?.ToObject<ParabolicMicrophoneTierTwoUnlocked>(),
                FlashlightTierTwoUnlocked = jObject["FlashlightTierTwoUnlocked"]?.ToObject<FlashlightTierTwoUnlocked>(),
                TripodTierTwoUnlocked = jObject["TripodTierTwoUnlocked"]?.ToObject<TripodTierTwoUnlocked>(),
                DOTSProjectorTierTwoUnlocked = jObject["DOTSProjectorTierTwoUnlocked"]?.ToObject<DOTSProjectorTierTwoUnlocked>(),
                ThermometerTierTwoUnlocked = jObject["ThermometerTierTwoUnlocked"]?.ToObject<ThermometerTierTwoUnlocked>(),
                FirelightTierTwoUnlocked = jObject["FirelightTierTwoUnlocked"]?.ToObject<FirelightTierTwoUnlocked>(),
                MotionSensorTierTwoUnlocked = jObject["MotionSensorTierTwoUnlocked"]?.ToObject<MotionSensorTierTwoUnlocked>(),
                PhotoCameraTierTwoUnlocked = jObject["PhotoCameraTierTwoUnlocked"]?.ToObject<PhotoCameraTierTwoUnlocked>(),
                SanityMedicationTierTwoUnlocked = jObject["SanityMedicationTierTwoUnlocked"]?.ToObject<SanityMedicationTierTwoUnlocked>(),
                RepellentTierThreeUnlocked = jObject["RepellentTierThreeUnlocked"]?.ToObject<RepellentTierThreeUnlocked>(),
                IgniterTierThreeUnlocked = jObject["IgniterTierThreeUnlocked"]?.ToObject<IgniterTierThreeUnlocked>(),
                SoundSensorTierThreeUnlocked = jObject["SoundSensorTierThreeUnlocked"]?.ToObject<SoundSensorTierThreeUnlocked>(),
                SpiritBoxTierThreeUnlocked = jObject["SpiritBoxTierThreeUnlocked"]?.ToObject<SpiritBoxTierThreeUnlocked>(),
                HeadGearTierThreeUnlocked = jObject["HeadGearTierThreeUnlocked"]?.ToObject<HeadGearTierThreeUnlocked>(),
                CrucifixTierThreeUnlocked = jObject["CrucifixTierThreeUnlocked"]?.ToObject<CrucifixTierThreeUnlocked>(),
                VideoCameraTierThreeUnlocked = jObject["VideoCameraTierThreeUnlocked"]?.ToObject<VideoCameraTierThreeUnlocked>(),
                GhostWritingBookTierThreeUnlocked = jObject["GhostWritingBookTierThreeUnlocked"]?.ToObject<GhostWritingBookTierThreeUnlocked>(),
                EMFReaderTierThreeUnlocked = jObject["EMFReaderTierThreeUnlocked"]?.ToObject<EMFReaderTierThreeUnlocked>(),
                UVLightTierThreeUnlocked = jObject["UVLightTierThreeUnlocked"]?.ToObject<UVLightTierThreeUnlocked>(),
                SaltTierThreeUnlocked = jObject["SaltTierThreeUnlocked"]?.ToObject<SaltTierThreeUnlocked>(),
                ParabolicMicrophoneTierThreeUnlocked = jObject["ParabolicMicrophoneTierThreeUnlocked"]?.ToObject<ParabolicMicrophoneTierThreeUnlocked>(),
                FlashlightTierThreeUnlocked = jObject["FlashlightTierThreeUnlocked"]?.ToObject<FlashlightTierThreeUnlocked>(),
                TripodTierThreeUnlocked = jObject["TripodTierThreeUnlocked"]?.ToObject<TripodTierThreeUnlocked>(),
                DOTSProjectorTierThreeUnlocked = jObject["DOTSProjectorTierThreeUnlocked"]?.ToObject<DOTSProjectorTierThreeUnlocked>(),
                ThermometerTierThreeUnlocked = jObject["ThermometerTierThreeUnlocked"]?.ToObject<ThermometerTierThreeUnlocked>(),
                FirelightTierThreeUnlocked = jObject["FirelightTierThreeUnlocked"]?.ToObject<FirelightTierThreeUnlocked>(),
                MotionSensorTierThreeUnlocked = jObject["MotionSensorTierThreeUnlocked"]?.ToObject<MotionSensorTierThreeUnlocked>(),
                PhotoCameraTierThreeUnlocked = jObject["PhotoCameraTierThreeUnlocked"]?.ToObject<PhotoCameraTierThreeUnlocked>(),
                SanityMedicationTierThreeUnlocked = jObject["SanityMedicationTierThreeUnlocked"]?.ToObject<SanityMedicationTierThreeUnlocked>(),
                RepellentTierOneUnlocked = jObject["RepellentTierOneUnlocked"]?.ToObject<RepellentTierOneUnlocked>(),
                IgniterTierOneUnlocked = jObject["IgniterTierOneUnlocked"]?.ToObject<IgniterTierOneUnlocked>(),
                SoundSensorTierOneUnlocked = jObject["SoundSensorTierOneUnlocked"]?.ToObject<SoundSensorTierOneUnlocked>(),
                SpiritBoxTierOneUnlocked = jObject["SpiritBoxTierOneUnlocked"]?.ToObject<SpiritBoxTierOneUnlocked>(),
                HeadGearTierOneUnlocked = jObject["HeadGearTierOneUnlocked"]?.ToObject<HeadGearTierOneUnlocked>(),
                CrucifixTierOneUnlocked = jObject["CrucifixTierOneUnlocked"]?.ToObject<CrucifixTierOneUnlocked>(),
                VideoCameraTierOneUnlocked = jObject["VideoCameraTierOneUnlocked"]?.ToObject<VideoCameraTierOneUnlocked>(),
                GhostWritingBookTierOneUnlocked = jObject["GhostWritingBookTierOneUnlocked"]?.ToObject<GhostWritingBookTierOneUnlocked>(),
                EMFReaderTierOneUnlocked = jObject["EMFReaderTierOneUnlocked"]?.ToObject<EMFReaderTierOneUnlocked>(),
                UVLightTierOneUnlocked = jObject["UVLightTierOneUnlocked"]?.ToObject<UVLightTierOneUnlocked>(),
                SaltTierOneUnlocked = jObject["SaltTierOneUnlocked"]?.ToObject<SaltTierOneUnlocked>(),
                ParabolicMicrophoneTierOneUnlocked = jObject["ParabolicMicrophoneTierOneUnlocked"]?.ToObject<ParabolicMicrophoneTierOneUnlocked>(),
                FlashlightTierOneUnlocked = jObject["FlashlightTierOneUnlocked"]?.ToObject<FlashlightTierOneUnlocked>(),
                TripodTierOneUnlocked = jObject["TripodTierOneUnlocked"]?.ToObject<TripodTierOneUnlocked>(),
                DOTSProjectorTierOneUnlocked = jObject["DOTSProjectorTierOneUnlocked"]?.ToObject<DOTSProjectorTierOneUnlocked>(),
                ThermometerTierOneUnlocked = jObject["ThermometerTierOneUnlocked"]?.ToObject<ThermometerTierOneUnlocked>(),
                FirelightTierOneUnlocked = jObject["FirelightTierOneUnlocked"]?.ToObject<FirelightTierOneUnlocked>(),
                MotionSensorTierOneUnlocked = jObject["MotionSensorTierOneUnlocked"]?.ToObject<MotionSensorTierOneUnlocked>(),
                PhotoCameraTierOneUnlocked = jObject["PhotoCameraTierOneUnlocked"]?.ToObject<PhotoCameraTierOneUnlocked>(),
                SanityMedicationTierOneUnlocked = jObject["SanityMedicationTierOneUnlocked"]?.ToObject<SanityMedicationTierOneUnlocked>()
            };
        }
    }
}
